import type { NextPage } from 'next'
import Head from 'next/head'

import NaverMap from '../components/NaverMap'

import wasteBetteryCollectorLatlngs from '../data/wasteBetteryCollectorLatlngs.json';

const Home: NextPage = () => {
  return (
    <div style={{width: '100%', height: '100%'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=1n27uhht04"></script>
      </Head>

      <NaverMap latlngs={wasteBetteryCollectorLatlngs} />
    </div>
  )
}

export default Home
